### ISSUE TITLE
Create a navbar with links

### ISSUE THREAD

**Issue by moogwol** [collectivenectar/pengen#4]
@collectivenectar if you think of anything that needs to be done, you can create an issue like this then it can be added to the project todo list [here.](https://github.com/collectivenectar/pengen/projects/1)

**Comment by collectivenectar** [comment]
Is this a real issue you'd want implemented? Or was this just related to the todo only? Because I can add a navbar if that's what's needed.

**Comment by moogwol** [comment]
Yes I think it would be good to have a nav-bar. It doesn't need to bee too complicated. We could maybe put the links for the landing page and the canvas page on it and the load drawing drop-down menu.

**Comment by collectivenectar** [comment]
I was thinking it would be cleaner to have the landing page as a link at the bottom for simplicity, and to redesign the layout so the load/save is in the top left corner as a hover style menu. 

This way the tools can be on their own and it will look cleaner. It would also provide extra room if we do decide to add other features, like a color history or color fill option. 

I've got a hover style menu that's working, but testing the save/load has been problematic for me in VScode, so I'd need to push an update every time I want to test. Maybe I can set up the UI and you can sort the save/load functions?

In the meantime, I will push what I have so you can see what I'm talking about. I haven't removed the old buttons yet(in case we don't like it or need to use code from it).

**Comment by collectivenectar** [comment]
Forgot to mention, I set it up so the title of the hover style menu is set to 'Untitled' just for accessibility, I thought this way once it's saved the 'Untitled' would change to the name the user gives. Just pushed an update so you can see what I'm talking about, it's currently a non-working save/load as far as I can tell, so  we'll have to talk tomorrow to sort it out.

**Comment by moogwol** [comment]
> I was thinking it would be cleaner to have the landing page as a link at the bottom for simplicity

Yeah that sounds good.

> Forgot to mention, I set it up so the title of the hover style menu is set to 'Untitled' just for accessibility, I thought this way once it's saved the 'Untitled' would change to the name the user gives.

I agree it works well like that.

**Comment by collectivenectar** [comment]
I've set the landing page and app to link to each other and so far it works, so I'm considering it closed for now.
