### ISSUE TITLE
Deploy the app to GitHub Pages

### ISSUE THREAD

**Issue by moogwol** [collectivenectar/pengen#5]
@collectivenectar I think you will have to do this because I don't have access  to the project settings

Details [here](https://pages.github.com/)

**Comment by moogwol** [comment]
@collectivenectar  If you're happy to use siasky then I think we can close this issue

**Comment by collectivenectar** [comment]
I would like to try siasky.net but I just want to see that a full stack will work well and doesn't have any lag. Maybe we can just use pages until we have something more full that's ready to deploy?

**Comment by moogwol** [comment]
Okay, I think you will have to do it because I don't have access to settings on this project

**Comment by moogwol** [comment]
Closing this since it was already done automatically 
![image](https://user-images.githubusercontent.com/25416419/142764831-ee8953fb-cb33-4f9b-a546-350c48df8e06.png)
